Repository xxchillkroetexx/DailyDashboard, pull requests merged in 2023-06, with the labels that each got.

#23 fixed some bugs and added comments
  client/src/MainPage.tsx
  client/src/components/GetWitz.tsx
  client/src/components/board-user.component.tsx
  client/src/components/home.component.tsx
  client/src/components/login.component.tsx
  client/src/components/profile.component.tsx
  client/src/components/register.component.tsx
  client/src/services/auth-header.tsx
  client/src/services/auth.service.tsx
  client/src/services/user.service.tsx
  client/src/types/user.type.ts
Labels: bug, documentation

#24 Wetter Panel ist integriert mit manuellem Standort
  client/src/components/WeatherPanel.tsx
  client/src/components/home.component.tsx
Labels: enhancement

#26 Jetzt mit location Abfrage im Browser, wobei bei Ablehnen des Browser Standorts die Stadt standardmäßig auf Mannheim gesetzt wird
  client/src/components/WeatherPanel.tsx
Labels: enhancement

#31 Frontend design
  client/src/Home.css
  client/src/MainPage.css
  client/src/MainPage.tsx
  client/src/components/WeatherPanel.tsx
  client/src/components/WitzePanel.component.tsx
  client/src/components/board-user.component.tsx
  client/src/components/home.component.tsx
  client/src/components/login.component.tsx
  client/src/components/register.component.tsx
  client/src/components/userboard.component.tsx
  client/src/services/GetWitz.service.tsx
  client/src/style/Background.jpg
  client/src/style/DD-Logo.png
  client/src/style/Home.css
  client/src/style/Login.css
  client/src/style/MainPage.css
  client/src/style/Register.css
  client/src/style/Userboard.css
  client/test/getWitz.test.js
Labels: enhancement

#32 Rss panel
  client/src/components/userboard.component.tsx
  client/src/services/RSS.service.tsx
  server/package-lock.json
  server/package.json
  server/src/index.ts
Labels: enhancement

#33 Finished design, added links to rss
  client/src/components/WeatherPanel.tsx
  client/src/components/home.component.tsx
  client/src/components/userboard.component.tsx
  client/src/services/RSS.service.tsx
  client/src/style/Home.css
  client/src/style/Userboard.css
  server/src/index.ts
Labels: enhancement

#39 Readme and Title updated
  README.md
  client/index.html
Labels: bug, enhancement
