Repository xxchillkroetexx/DailyDashboard, pull requests merged in 2023-05, with the labels that each got.

#4 created joke API endpoint
  server/package-lock.json
  server/package.json
  server/src/index.ts
Labels: enhancement

#12 Login with cookies
  client/package-lock.json
  client/package.json
  client/src/Home.css
  client/src/MainPage.css
  client/src/MainPage.tsx
  client/src/common/EventBus.tsx
  client/src/components/SiteHeader.tsx
  client/src/components/board-user.component.tsx
  client/src/components/home.component.tsx
  client/src/components/login.component.tsx
  client/src/components/profile.component.tsx
  client/src/components/register.component.tsx
  client/src/index.css
  client/src/main.tsx
  client/src/reportWebVitals.ts
  client/src/services/auth-header.tsx
  client/src/services/auth.service.tsx
  client/src/services/user.service.tsx
  client/src/types/user.type.ts
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/src/models/UserSchema.ts
Labels: enhancement, question

#13 Funktionen der test
  client/babel.config.cjs
  client/jest.config.ts
  client/package.json
  client/test/register.test.js
  client/tsconfig.json
Labels: enhancement

#14 update mit Witzen
  client/src/components/GetWitz.tsx
  client/src/components/WitzePanel.tsx
  client/src/components/home.component.tsx
Labels: enhancement

#16 Login auth header
  client/package-lock.json
  client/package.json
  client/src/services/auth.service.tsx
  client/src/services/cookie-util.ts
  server/src/index.ts
  server/src/models/CredentialsSchema.ts
Labels: enhancement

#18 functional db connection unit test
  server/babel.config.cjs
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/src/index.ts
  server/test/db-connection.test.js
Labels: documentation

#20 Unit test get witze
  client/package.json
  client/src/components/GetWitz.tsx
  client/test/getWitz.test.js
  client/test/register.test.js
Labels: documentation

#21 Unit test login/register
  client/src/components/login.component.tsx
  client/src/components/register.component.tsx
  client/test/getWitz.test.js
  client/test/login.test.js
  client/test/register.test.js
Labels: documentation
